In [2]:
import numpy as np
import pandas as pd
pd.set_option("display.max_columns", None)

In [3]:
import os
os.listdir("../data/raw")

['ai_jobs_market_2025_2026.csv']

In [4]:
df = pd.read_csv("../data/raw/ai_jobs_market_2025_2026.csv")
df

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,country,remote_work,company_size,industry,required_skills,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,USA,On-site,Startup (1-50),Finance,APIs|Planning Systems|Python|Cloud|SQL|Leadership,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,UK,Hybrid,Enterprise (5000+),Finance,Python|Documentation|LLM APIs|Prompt Design|NL...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,USA,Fully Remote,Big Tech (FAANG+),Finance,Vector DBs|Python|Prompt Engineering|Fine-tuni...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3,Bachelor's,161000.0,130000,220000,Singapore,Singapore,Fully Remote,SME (51-500),Technology,Feature Stores|Spark|ETL|Airflow|dbt|SQL|Pytho...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,USA,Fully Remote,Enterprise (5000+),Automotive,Data Analysis|Stakeholder Mgmt|Agile|Cloud|Pro...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,AIJOB1496,Multimodal AI Engineer,AI Engineering,Lead (10+ yrs),8,Master's,262000.0,160000,300000,Toronto,Canada,Hybrid,SME (51-500),Retail,Python|Vision-Language Models|Fine-tuning|PyTo...,8.8,90,23.6,7.5,2026,1,1,1,0,Senior ($200-300k)
1496,AIJOB1497,NLP Engineer,AI Engineering,Senior (6-9 yrs),9,Bootcamp/Self-taught,163000.0,145000,290000,Berlin,Germany,On-site,Mid-size (501-5000),Manufacturing,Transformers|Text Processing|LLMs|Hugging Face...,6.7,91,66.5,7.8,2025,3,1,0,0,Upper-Mid ($150-200k)
1497,AIJOB1498,AI Compliance Manager,Governance,Mid (3-5 yrs),10,Master's,127000.0,100000,200000,Zurich,Switzerland,Hybrid,SME (51-500),Manufacturing,Documentation|Risk Management|Legal Knowledge|...,10.9,68,15.3,8.3,2026,3,0,1,0,Mid ($100-150k)
1498,AIJOB1499,NLP Engineer,AI Engineering,Lead (10+ yrs),4,Bachelor's,145000.0,145000,290000,Bangalore,India,Hybrid,Enterprise (5000+),Media,LLMs|Hugging Face|Python|Transformers|BERT|Tex...,8.5,91,78.8,7.4,2025,5,1,1,0,Mid ($100-150k)
1499,AIJOB1500,AI Security Engineer,Security,Lead (10+ yrs),5,Master's,229000.0,140000,260000,Berlin,Germany,Hybrid,Enterprise (5000+),Technology,Cybersecurity|ML Security|Red Teaming|Python|R...,12.2,80,9.0,8.6,2025,6,1,1,0,Senior ($200-300k)

In [9]:
df.head()

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,country,remote_work,company_size,industry,required_skills,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,USA,On-site,Startup (1-50),Finance,APIs|Planning Systems|Python|Cloud|SQL|Leadership,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,UK,Hybrid,Enterprise (5000+),Finance,Python|Documentation|LLM APIs|Prompt Design|NL...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,USA,Fully Remote,Big Tech (FAANG+),Finance,Vector DBs|Python|Prompt Engineering|Fine-tuni...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3,Bachelor's,161000.0,130000,220000,Singapore,Singapore,Fully Remote,SME (51-500),Technology,Feature Stores|Spark|ETL|Airflow|dbt|SQL|Pytho...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,USA,Fully Remote,Enterprise (5000+),Automotive,Data Analysis|Stakeholder Mgmt|Agile|Cloud|Pro...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)

In [11]:
df.shape

(1500, 25)

In [12]:
df.columns

Index(['job_id', 'job_title', 'job_category', 'experience_level',
       'years_of_experience', 'education_required', 'annual_salary_usd',
       'salary_min_usd', 'salary_max_usd', 'city', 'country', 'remote_work',
       'company_size', 'industry', 'required_skills', 'ai_salary_premium_pct',
       'demand_score', 'demand_growth_yoy_pct', 'benefits_score_10',
       'posting_year', 'posting_month', 'is_senior', 'is_remote_friendly',
       'is_llm_role', 'salary_tier'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_id                 1500 non-null   object
 1   job_title              1500 non-null   object
 2   job_category           1500 non-null   object
 3   experience_level       1500 non-null   object
 4   years_of_experience    1500 non-null   int64
 5   education_required     1500 non-null   object
 6   annual_salary_usd      1500 non-null   float64
 7   salary_min_usd         1500 non-null   int64
 8   salary_max_usd         1500 non-null   int64
 9   city                   1500 non-null   object
 10  country                1500 non-null   object
 11  remote_work            1500 non-null   object
 12  company_size           1500 non-null   object
 13  industry               1500 non-null   object
 14  required_skills        1500 non-null   object
 15  ai_salary_premium_pct  1500 non-null   float64
 16  demand_score           1500 non-null   int64
 17  demand_growth_yoy_pct  1500 non-null   float64
 18  benefits_score_10      1500 non-null   float64
 19  posting_year           1500 non-null   int64
 20  posting_month          1500 non-null   int64
 21  is_senior              1500 non-null   int64
 22  is_remote_friendly     1500 non-null   int64
 23  is_llm_role            1500 non-null   int64
 24  salary_tier            1500 non-null   object
dtypes: float64(4), int64(9), object(12)
memory usage: 293.1+ KB

In [14]:
df.dtypes

job_id                    object
job_title                 object
job_category              object
experience_level          object
years_of_experience        int64
education_required        object
annual_salary_usd        float64
salary_min_usd             int64
salary_max_usd             int64
city                      object
country                   object
remote_work               object
company_size              object
industry                  object
required_skills           object
ai_salary_premium_pct    float64
demand_score               int64
demand_growth_yoy_pct    float64
benefits_score_10        float64
posting_year               int64
posting_month              int64
is_senior                  int64
is_remote_friendly         int64
is_llm_role                int64
salary_tier               object
dtype: object

In [15]:
df.describe()

,years_of_experience,annual_salary_usd,salary_min_usd,salary_max_usd,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,6.216000,194892.000000,135448.666667,257537.333333,10.858200,87.523333,31.116333,7.897333,2025.584000,3.968000,0.496667,0.754000,0.218000
std,2.675216,66506.822013,24448.950878,39852.822207,4.029742,8.026315,22.046343,1.102846,0.493058,3.270388,0.500156,0.430822,0.413025
min,1.000000,90000.000000,90000.000000,180000.000000,3.000000,68.000000,5.000000,6.000000,2025.000000,1.000000,0.000000,0.000000,0.000000
25%,4.000000,144750.000000,120000.000000,218000.000000,8.200000,82.000000,15.375000,6.900000,2025.000000,2.000000,0.000000,1.000000,0.000000
50%,6.000000,180000.000000,140000.000000,270000.000000,10.500000,89.000000,23.400000,7.900000,2026.000000,3.000000,0.000000,1.000000,0.000000
75%,8.000000,236250.000000,155000.000000,290000.000000,14.200000,95.000000,42.700000,8.900000,2026.000000,5.000000,1.000000,1.000000,0.000000
max,15.000000,384000.000000,180000.000000,320000.000000,18.000000,98.000000,87.800000,9.800000,2026.000000,12.000000,1.000000,1.000000,1.000000

In [16]:
df.describe(include="object")

,job_id,job_title,job_category,experience_level,education_required,city,country,remote_work,company_size,industry,required_skills,salary_tier
count,1500,1500,1500,1500,1500,1500,1500,1500,1500,1500,1500,1500
unique,1500,25,12,4,5,20,14,3,5,12,1500,5
top,AIJOB1500,LLM Engineer,AI Engineering,Entry (0-2 yrs),Master's,San Francisco,USA,Hybrid,Mid-size (501-5000),Automotive,Cybersecurity|ML Security|Red Teaming|Python|R...,Senior ($200-300k)
freq,1,75,736,385,316,92,515,686,312,138,1,467

In [17]:
df.isnull().sum()

job_id                   0
job_title                0
job_category             0
experience_level         0
years_of_experience      0
education_required       0
annual_salary_usd        0
salary_min_usd           0
salary_max_usd           0
city                     0
country                  0
remote_work              0
company_size             0
industry                 0
required_skills          0
ai_salary_premium_pct    0
demand_score             0
demand_growth_yoy_pct    0
benefits_score_10        0
posting_year             0
posting_month            0
is_senior                0
is_remote_friendly       0
is_llm_role              0
salary_tier              0
dtype: int64

In [18]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1495    False
1496    False
1497    False
1498    False
1499    False
Length: 1500, dtype: bool

In [19]:
df["job_category"].unique()

array(['AI Engineering', 'Data Engineering', 'Product', 'Security',
       'Architecture', 'ML Operations', 'Business', 'Robotics',
       'Data Science', 'Governance', 'Infrastructure', 'Research'],
      dtype=object)

In [21]:
df["experience_level"].unique()

array(['Senior (6-9 yrs)', 'Lead (10+ yrs)', 'Entry (0-2 yrs)',
       'Mid (3-5 yrs)'], dtype=object)

In [22]:
df["remote_work"].unique()

array(['On-site', 'Hybrid', 'Fully Remote'], dtype=object)

In [23]:
df["country"].unique()

array(['USA', 'UK', 'Singapore', 'Global', 'India', 'Japan', 'China',
       'Canada', 'UAE', 'Netherlands', 'France', 'Australia', 'Germany',
       'Switzerland'], dtype=object)

In [24]:
df["industry"].unique()

array(['Finance', 'Technology', 'Automotive', 'Government',
       'Manufacturing', 'Education', 'Retail', 'Consulting', 'Research',
       'Healthcare', 'Media', 'Energy'], dtype=object)

In [25]:
df["experience_level"].value_counts()

experience_level
Entry (0-2 yrs)     385
Lead (10+ yrs)      381
Mid (3-5 yrs)       370
Senior (6-9 yrs)    364
Name: count, dtype: int64

In [26]:
df["remote_work"].value_counts()

remote_work
Hybrid          686
Fully Remote    445
On-site         369
Name: count, dtype: int64

In [27]:
df["job_category"].value_counts()

job_category
AI Engineering      736
Data Science        127
Governance          122
Robotics             74
Product              70
Business             62
Infrastructure       55
Architecture         52
ML Operations        51
Data Engineering     51
Security             50
Research             50
Name: count, dtype: int64

# ## Initial Observations

- The dataset contains 1500 job records.
- The dataset contains 25 columns.
- The dataset contains information about job roles, salaries, skills, experience, location and remote work.
- Salary and experience are important numerical variables.
- Job category, country, industry and remote work are categorical variables.
- Missing values and duplicate records will be investigated further during the data quality phase.