In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df = pd.read_csv("../data/raw/ai_jobs_market_2025_2026.csv")
df

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,...,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,...,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3,Bachelor's,161000.0,130000,220000,Singapore,...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,AIJOB1496,Multimodal AI Engineer,AI Engineering,Lead (10+ yrs),8,Master's,262000.0,160000,300000,Toronto,...,8.8,90,23.6,7.5,2026,1,1,1,0,Senior ($200-300k)
1496,AIJOB1497,NLP Engineer,AI Engineering,Senior (6-9 yrs),9,Bootcamp/Self-taught,163000.0,145000,290000,Berlin,...,6.7,91,66.5,7.8,2025,3,1,0,0,Upper-Mid ($150-200k)
1497,AIJOB1498,AI Compliance Manager,Governance,Mid (3-5 yrs),10,Master's,127000.0,100000,200000,Zurich,...,10.9,68,15.3,8.3,2026,3,0,1,0,Mid ($100-150k)
1498,AIJOB1499,NLP Engineer,AI Engineering,Lead (10+ yrs),4,Bachelor's,145000.0,145000,290000,Bangalore,...,8.5,91,78.8,7.4,2025,5,1,1,0,Mid ($100-150k)
1499,AIJOB1500,AI Security Engineer,Security,Lead (10+ yrs),5,Master's,229000.0,140000,260000,Berlin,...,12.2,80,9.0,8.6,2025,6,1,1,0,Senior ($200-300k)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_id                 1500 non-null   object
 1   job_title              1500 non-null   object
 2   job_category           1500 non-null   object
 3   experience_level       1500 non-null   object
 4   years_of_experience    1500 non-null   int64
 5   education_required     1500 non-null   object
 6   annual_salary_usd      1500 non-null   float64
 7   salary_min_usd         1500 non-null   int64
 8   salary_max_usd         1500 non-null   int64
 9   city                   1500 non-null   object
 10  country                1500 non-null   object
 11  remote_work            1500 non-null   object
 12  company_size           1500 non-null   object
 13  industry               1500 non-null   object
 14  required_skills        1500 non-null   object
 15  ai_salary_premium_pct  1500 non-null   float64
 16  demand_score           1500 non-null   int64
 17  demand_growth_yoy_pct  1500 non-null   float64
 18  benefits_score_10      1500 non-null   float64
 19  posting_year           1500 non-null   int64
 20  posting_month          1500 non-null   int64
 21  is_senior              1500 non-null   int64
 22  is_remote_friendly     1500 non-null   int64
 23  is_llm_role            1500 non-null   int64
 24  salary_tier            1500 non-null   object
dtypes: float64(4), int64(9), object(12)
memory usage: 293.1+ KB

In [26]:
clean_df = df.copy()

In [27]:
print("Rows:",clean_df.shape[0])
print("Columns:",clean_df.shape[1])

Rows: 1500
Columns: 25

In [28]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_id                 1500 non-null   object
 1   job_title              1500 non-null   object
 2   job_category           1500 non-null   object
 3   experience_level       1500 non-null   object
 4   years_of_experience    1500 non-null   int64
 5   education_required     1500 non-null   object
 6   annual_salary_usd      1500 non-null   float64
 7   salary_min_usd         1500 non-null   int64
 8   salary_max_usd         1500 non-null   int64
 9   city                   1500 non-null   object
 10  country                1500 non-null   object
 11  remote_work            1500 non-null   object
 12  company_size           1500 non-null   object
 13  industry               1500 non-null   object
 14  required_skills        1500 non-null   object
 15  ai_salary_premium_pct  1500 non-null   float64
 16  demand_score           1500 non-null   int64
 17  demand_growth_yoy_pct  1500 non-null   float64
 18  benefits_score_10      1500 non-null   float64
 19  posting_year           1500 non-null   int64
 20  posting_month          1500 non-null   int64
 21  is_senior              1500 non-null   int64
 22  is_remote_friendly     1500 non-null   int64
 23  is_llm_role            1500 non-null   int64
 24  salary_tier            1500 non-null   object
dtypes: float64(4), int64(9), object(12)
memory usage: 293.1+ KB

In [29]:
clean_df.columns

Index(['job_id', 'job_title', 'job_category', 'experience_level',
       'years_of_experience', 'education_required', 'annual_salary_usd',
       'salary_min_usd', 'salary_max_usd', 'city', 'country', 'remote_work',
       'company_size', 'industry', 'required_skills', 'ai_salary_premium_pct',
       'demand_score', 'demand_growth_yoy_pct', 'benefits_score_10',
       'posting_year', 'posting_month', 'is_senior', 'is_remote_friendly',
       'is_llm_role', 'salary_tier'],
      dtype='object')

In [30]:
clean_df.columns = (
    clean_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
clean_df.columns

Index(['job_id', 'job_title', 'job_category', 'experience_level',
       'years_of_experience', 'education_required', 'annual_salary_usd',
       'salary_min_usd', 'salary_max_usd', 'city', 'country', 'remote_work',
       'company_size', 'industry', 'required_skills', 'ai_salary_premium_pct',
       'demand_score', 'demand_growth_yoy_pct', 'benefits_score_10',
       'posting_year', 'posting_month', 'is_senior', 'is_remote_friendly',
       'is_llm_role', 'salary_tier'],
      dtype='object')

In [31]:
text_columns = clean_df.select_dtypes(include="object").columns
text_columns

Index(['job_id', 'job_title', 'job_category', 'experience_level',
       'education_required', 'city', 'country', 'remote_work', 'company_size',
       'industry', 'required_skills', 'salary_tier'],
      dtype='object')

In [32]:
for col in text_columns:
    clean_df[col] = clean_df[col].str.strip()

In [33]:
# Missing Values ka Percentage
missing_percentage = (
    clean_df.isnull().sum() / len(clean_df) * 100
)
missing_percentage[missing_percentage > 0]

Series([], dtype: float64)

In [34]:
# Missing values handle 
clean_df["education_required"] = (
    clean_df["education_required"]
    .fillna("Unknown")
)
clean_df

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,...,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,...,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3,Bachelor's,161000.0,130000,220000,Singapore,...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,AIJOB1496,Multimodal AI Engineer,AI Engineering,Lead (10+ yrs),8,Master's,262000.0,160000,300000,Toronto,...,8.8,90,23.6,7.5,2026,1,1,1,0,Senior ($200-300k)
1496,AIJOB1497,NLP Engineer,AI Engineering,Senior (6-9 yrs),9,Bootcamp/Self-taught,163000.0,145000,290000,Berlin,...,6.7,91,66.5,7.8,2025,3,1,0,0,Upper-Mid ($150-200k)
1497,AIJOB1498,AI Compliance Manager,Governance,Mid (3-5 yrs),10,Master's,127000.0,100000,200000,Zurich,...,10.9,68,15.3,8.3,2026,3,0,1,0,Mid ($100-150k)
1498,AIJOB1499,NLP Engineer,AI Engineering,Lead (10+ yrs),4,Bachelor's,145000.0,145000,290000,Bangalore,...,8.5,91,78.8,7.4,2025,5,1,1,0,Mid ($100-150k)
1499,AIJOB1500,AI Security Engineer,Security,Lead (10+ yrs),5,Master's,229000.0,140000,260000,Berlin,...,12.2,80,9.0,8.6,2025,6,1,1,0,Senior ($200-300k)

## Duplicate Records

In [35]:
clean_df.duplicated().sum()

np.int64(0)

In [36]:
clean_df["job_id"].duplicated().sum()

np.int64(0)

In [37]:
# Data types fix 
numeric_columns = [
    "years_of_experience",
    "annual_salary_usd",
    "salary_min_usd",
    "salary_max_usd",
    "ai_salary_premium_pct",
    "demand_score",
    "demand_growth_yoy_pct",
    "benefits_score_10",
    "posting_year"
]

In [38]:
for col in numeric_columns:
    clean_df[col] = pd.to_numeric(
        clean_df[col],
        errors="coerce"
    )

clean_df[numeric_columns].dtypes

years_of_experience        int64
annual_salary_usd        float64
salary_min_usd             int64
salary_max_usd             int64
ai_salary_premium_pct    float64
demand_score               int64
demand_growth_yoy_pct    float64
benefits_score_10        float64
posting_year               int64
dtype: object

In [39]:
# Boolean Columns Check
boolean_columns = [
    "is_senior",
    "is_remote_friendly",
    "is_llm_role"
]

for col in boolean_columns:
    print()
    print(clean_df[col].value_counts(dropna=False))

is_senior
0    755
1    745
Name: count, dtype: int64

is_remote_friendly
1    1131
0     369
Name: count, dtype: int64

is_llm_role
0    1173
1     327
Name: count, dtype: int64

In [40]:
# Invalid Salary Values
clean_df.loc[
    
    clean_df["annual_salary_usd"] < 0,
    "annual_salary_usd"
] = np.nan
clean_df

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,...,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,...,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3,Bachelor's,161000.0,130000,220000,Singapore,...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,AIJOB1496,Multimodal AI Engineer,AI Engineering,Lead (10+ yrs),8,Master's,262000.0,160000,300000,Toronto,...,8.8,90,23.6,7.5,2026,1,1,1,0,Senior ($200-300k)
1496,AIJOB1497,NLP Engineer,AI Engineering,Senior (6-9 yrs),9,Bootcamp/Self-taught,163000.0,145000,290000,Berlin,...,6.7,91,66.5,7.8,2025,3,1,0,0,Upper-Mid ($150-200k)
1497,AIJOB1498,AI Compliance Manager,Governance,Mid (3-5 yrs),10,Master's,127000.0,100000,200000,Zurich,...,10.9,68,15.3,8.3,2026,3,0,1,0,Mid ($100-150k)
1498,AIJOB1499,NLP Engineer,AI Engineering,Lead (10+ yrs),4,Bachelor's,145000.0,145000,290000,Bangalore,...,8.5,91,78.8,7.4,2025,5,1,1,0,Mid ($100-150k)
1499,AIJOB1500,AI Security Engineer,Security,Lead (10+ yrs),5,Master's,229000.0,140000,260000,Berlin,...,12.2,80,9.0,8.6,2025,6,1,1,0,Senior ($200-300k)

In [41]:
# Experience validate 
clean_df.loc[
    clean_df["years_of_experience"] < 0,
    "years_of_experience"
] = np.nan
clean_df

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,...,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7.0,Master's,239000.0,155000,290000,Boston,...,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2.0,Bachelor's,166000.0,90000,200000,London,...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4.0,Associate's,360000.0,160000,300000,Seattle,...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3.0,Bachelor's,161000.0,130000,220000,Singapore,...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5.0,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,AIJOB1496,Multimodal AI Engineer,AI Engineering,Lead (10+ yrs),8.0,Master's,262000.0,160000,300000,Toronto,...,8.8,90,23.6,7.5,2026,1,1,1,0,Senior ($200-300k)
1496,AIJOB1497,NLP Engineer,AI Engineering,Senior (6-9 yrs),9.0,Bootcamp/Self-taught,163000.0,145000,290000,Berlin,...,6.7,91,66.5,7.8,2025,3,1,0,0,Upper-Mid ($150-200k)
1497,AIJOB1498,AI Compliance Manager,Governance,Mid (3-5 yrs),10.0,Master's,127000.0,100000,200000,Zurich,...,10.9,68,15.3,8.3,2026,3,0,1,0,Mid ($100-150k)
1498,AIJOB1499,NLP Engineer,AI Engineering,Lead (10+ yrs),4.0,Bachelor's,145000.0,145000,290000,Bangalore,...,8.5,91,78.8,7.4,2025,5,1,1,0,Mid ($100-150k)
1499,AIJOB1500,AI Security Engineer,Security,Lead (10+ yrs),5.0,Master's,229000.0,140000,260000,Berlin,...,12.2,80,9.0,8.6,2025,6,1,1,0,Senior ($200-300k)

In [69]:
# Benefits Score Validate 
clean_df.loc[
    (clean_df["benefits_score_10"] < 0) |
    (clean_df["benefits_score_10"] < 0),
    "benefits_score_10"
] = np.nan

clean_df["benefits_score_10"]

0       6.8
1       6.2
2       7.7
3       9.5
4       8.9
       ...
1495    7.5
1496    7.8
1497    8.3
1498    7.4
1499    8.6
Name: benefits_score_10, Length: 1500, dtype: float64

## Categorical Values Standardize karna

In [44]:
clean_df["country"].value_counts()

country
USA            515
UK              90
China           87
Canada          85
Global          82
Germany         81
Australia       78
Switzerland     76
Japan           76
Netherlands     74
Singapore       71
France          66
UAE             62
India           57
Name: count, dtype: int64

In [45]:
# Text cleanup
clean_df["country"] = (
    clean_df["country"]
    .str.strip()
    .str.title()
)
clean_df["country"]

0               Usa
1                Uk
2               Usa
3         Singapore
4               Usa
           ...
1495         Canada
1496        Germany
1497    Switzerland
1498          India
1499        Germany
Name: country, Length: 1500, dtype: object

In [46]:
# Remote Work
clean_df["remote_work"].value_counts()

remote_work
Hybrid          686
Fully Remote    445
On-site         369
Name: count, dtype: int64

In [47]:
clean_df["remote_work"] = (
    clean_df["remote_work"]
    .str.strip()
    .str.title()
)
clean_df["remote_work"]

0            On-Site
1             Hybrid
2       Fully Remote
3       Fully Remote
4       Fully Remote
            ...
1495          Hybrid
1496         On-Site
1497          Hybrid
1498          Hybrid
1499          Hybrid
Name: remote_work, Length: 1500, dtype: object

In [48]:
## Experience Level
clean_df["experience_level"].value_counts()

experience_level
Entry (0-2 yrs)     385
Lead (10+ yrs)      381
Mid (3-5 yrs)       370
Senior (6-9 yrs)    364
Name: count, dtype: int64

In [49]:
clean_df["experience_level"] = (
    clean_df["experience_level"]
    .str.strip()
)
clean_df["experience_level"]

0       Senior (6-9 yrs)
1       Senior (6-9 yrs)
2       Senior (6-9 yrs)
3       Senior (6-9 yrs)
4         Lead (10+ yrs)
              ...
1495      Lead (10+ yrs)
1496    Senior (6-9 yrs)
1497       Mid (3-5 yrs)
1498      Lead (10+ yrs)
1499      Lead (10+ yrs)
Name: experience_level, Length: 1500, dtype: object

In [50]:
# Job title
clean_df["job_category"].value_counts()

job_category
AI Engineering      736
Data Science        127
Governance          122
Robotics             74
Product              70
Business             62
Infrastructure       55
Architecture         52
ML Operations        51
Data Engineering     51
Security             50
Research             50
Name: count, dtype: int64

In [51]:
clean_df["job_category"] = (
    clean_df["job_category"]
    .str.strip()
)
clean_df["job_category"]

0         AI Engineering
1         AI Engineering
2         AI Engineering
3       Data Engineering
4                Product
              ...
1495      AI Engineering
1496      AI Engineering
1497          Governance
1498      AI Engineering
1499            Security
Name: job_category, Length: 1500, dtype: object

In [52]:
# Industry
clean_df["industry"].value_counts()

industry
Automotive       138
Healthcare       138
Government       136
Finance          131
Retail           131
Energy           130
Consulting       126
Media            120
Education        120
Manufacturing    114
Research         110
Technology       106
Name: count, dtype: int64

In [53]:
clean_df["industry"] = (
    clean_df["industry"] 
    .str.strip()
)
clean_df["industry"]

0             Finance
1             Finance
2             Finance
3          Technology
4          Automotive
            ...
1495           Retail
1496    Manufacturing
1497    Manufacturing
1498            Media
1499       Technology
Name: industry, Length: 1500, dtype: object

In [54]:
# Outliers
Q1 = clean_df["annual_salary_usd"].quantile(0.25)
Q3 = clean_df["annual_salary_usd"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [55]:
salary_outliers = clean_df[
    (clean_df["annual_salary_usd"] < lower_bound) |
    (clean_df["annual_salary_usd"] > upper_bound)
]

salary_outliers

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,...,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
83,AIJOB0084,Senior ML Engineer,AI Engineering,Senior (6-9 yrs),11.0,Master's,374400.0,180000,312000,New York,...,12.5,NaN,65.3,6.6,2026,2,1,1,0,Elite (>$300k)
647,AIJOB0648,Senior ML Engineer,AI Engineering,Senior (6-9 yrs),9.0,Master's,374400.0,180000,312000,Chicago,...,13.5,NaN,51.4,6.5,2026,2,1,1,0,Elite (>$300k)
822,AIJOB0823,AI Solutions Architect,Architecture,Lead (10+ yrs),11.0,PhD,384000.0,180000,320000,Dubai,...,10.4,NaN,14.7,6.3,2026,3,1,1,0,Elite (>$300k)
843,AIJOB0844,Senior ML Engineer,AI Engineering,Lead (10+ yrs),6.0,Bachelor's,374400.0,180000,312000,Paris,...,11.9,NaN,83.9,8.5,2026,3,1,1,0,Elite (>$300k)
896,AIJOB0897,AI Solutions Architect,Architecture,Lead (10+ yrs),8.0,PhD,384000.0,180000,320000,Toronto,...,16.4,NaN,15.5,9.1,2025,1,1,0,0,Elite (>$300k)
944,AIJOB0945,Senior ML Engineer,AI Engineering,Lead (10+ yrs),5.0,PhD,374400.0,180000,312000,Boston,...,11.7,NaN,19.1,9.6,2025,4,1,1,0,Elite (>$300k)
992,AIJOB0993,Senior ML Engineer,AI Engineering,Lead (10+ yrs),11.0,Master's,374400.0,180000,312000,Toronto,...,11.5,NaN,73.3,6.2,2025,6,1,0,0,Elite (>$300k)
1374,AIJOB1375,AI Solutions Architect,Architecture,Lead (10+ yrs),13.0,Master's,384000.0,180000,320000,New York,...,14.0,NaN,9.3,8.5,2025,9,1,0,0,Elite (>$300k)

In [74]:
clean_df.shape

(1500, 25)

In [84]:
clean_df.isnull().sum()

job_id                      0
job_title                   0
job_category                0
experience_level            0
years_of_experience         0
education_required          0
annual_salary_usd           0
salary_min_usd              0
salary_max_usd              0
city                        0
country                     0
remote_work                 0
company_size                0
industry                    0
required_skills             0
ai_salary_premium_pct       0
demand_score             1500
demand_growth_yoy_pct       0
benefits_score_10           0
posting_year                0
posting_month               0
is_senior                   0
is_remote_friendly          0
is_llm_role                 0
salary_tier                 0
dtype: int64

In [82]:
clean_df.duplicated().sum()

np.int64(0)

In [62]:
clean_df.dtypes

job_id                    object
job_title                 object
job_category              object
experience_level          object
years_of_experience      float64
education_required        object
annual_salary_usd        float64
salary_min_usd             int64
salary_max_usd             int64
city                      object
country                   object
remote_work               object
company_size              object
industry                  object
required_skills           object
ai_salary_premium_pct    float64
demand_score             float64
demand_growth_yoy_pct    float64
benefits_score_10        float64
posting_year               int64
posting_month              int64
is_senior                  int64
is_remote_friendly         int64
is_llm_role                int64
salary_tier               object
dtype: object

In [63]:
clean_df.describe()

,years_of_experience,annual_salary_usd,salary_min_usd,salary_max_usd,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,0.0,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,6.216000,194892.000000,135448.666667,257537.333333,10.858200,NaN,31.116333,7.897333,2025.584000,3.968000,0.496667,0.754000,0.218000
std,2.675216,66506.822013,24448.950878,39852.822207,4.029742,NaN,22.046343,1.102846,0.493058,3.270388,0.500156,0.430822,0.413025
min,1.000000,90000.000000,90000.000000,180000.000000,3.000000,NaN,5.000000,6.000000,2025.000000,1.000000,0.000000,0.000000,0.000000
25%,4.000000,144750.000000,120000.000000,218000.000000,8.200000,NaN,15.375000,6.900000,2025.000000,2.000000,0.000000,1.000000,0.000000
50%,6.000000,180000.000000,140000.000000,270000.000000,10.500000,NaN,23.400000,7.900000,2026.000000,3.000000,0.000000,1.000000,0.000000
75%,8.000000,236250.000000,155000.000000,290000.000000,14.200000,NaN,42.700000,8.900000,2026.000000,5.000000,1.000000,1.000000,0.000000
max,15.000000,384000.000000,180000.000000,320000.000000,18.000000,NaN,87.800000,9.800000,2026.000000,12.000000,1.000000,1.000000,1.000000

In [83]:
print("Original Shape:", df.shape)
print("Cleaned Shape :", clean_df.shape)

Original Shape: (1500, 25)
Cleaned Shape : (1500, 25)

In [65]:
final_missing = clean_df.isnull().sum()

final_missing[final_missing > 0]

demand_score    1500
dtype: int64

In [66]:
# Save clean dataset
clean_df.to_csv(
    "../data/processed/ai_jobs_cleaned.csv",
    index=False
)

In [67]:
import os

os.path.exists(
    "../data/processed/ai_jobs_cleaned.csv"
)

True